### ISSUE TITLE
Assigning 'related' model members is not saved

### ISSUE THREAD

**Issue by rodolforg** [taq/torm#10]
Suppose I have two models (User and Account) and they are related to each other:
User::hasMany('ticket')
Ticket::belongsTo('user')

// If I do this:
$ticket = Ticket::first();
print_r($ticket->user->id); // eg. 2
// It works just fine, but
$ticket->user = User::find(13);
print_r($ticket->user->id);
// It prints the previous$ticket->user info (eg. 2), instead of the new one.
Even if I save after changing $ticket->user.

I tried $ticket->setUser($user) (as Propel ORM does), but it didn't work also.
The only way is to explicitly assign the new value to $ticket->user_id.

Maybe the implementation of _resolveBelongsTo and alike does not overload 'set' methods.

**Comment by taq** [comment]
You're right. Please check the last commit and see if it worked.

**Comment by rodolforg** [comment]
It works great, thank you.
I did not test hasMany() neither hasOne() cases.

By the way, Propel ORM implements $user->addTicket($ticket) as alternative method to $ticket->setUser($user).

**Comment by taq** [comment]
Cool, glad it worked.
I think hasMany and hasOne, as aren't assigned methods like the belongsTo case, won't have such a problem. The `add` name sounds weird because looks like you can add more than one user on this case. :-)

**Comment by rodolforg** [comment]
I meant <add> _tickets_ to _user_ , as _user_ has many _ticket_s.
