### ISSUE TITLE
Empty collection says current position is valid

### ISSUE THREAD

**Issue by rodolforg** [taq/torm#11]
`$collection->valid()` is true due constructor implementation.
The value is only updated after a `next()` - or first `current()` - call.
This makes a `foreach` loop iterate once, but with *null* element.

**Comment by taq** [comment]
Thanks for finding this. Any suggestions? If we change to `false` on the constructor, seems it will never return to `foreach`.

**Comment by taq** [comment]
Hey, please check the `issue11` branch here and check if everything is working.

**Comment by rodolforg** [comment]
It works. Thank you again.

**Comment by taq** [comment]
Cool! I'll need to make a double checking if it's working fine on a large collection and will merge it.

**Comment by taq** [comment]
Seems it s ok, closing here.
