### ISSUE TITLE
Problema de Conexão com o Oracle

### ISSUE THREAD

**Issue by cgarrotti** [taq/torm#16]
Ola !
Estou tentando utilizar o Oracle no framework, porém acontece um erro dentro do Model.php

Fatal error: Call to a member function fetch() on boolean in C:\xampp\htdocs\sistema\torm\src\Model.php on line 393

teste_oracle.php
--------------------------
<?php

require_once "vendor/autoload.php";
require_once "models/pessoa.php";

	$tns = "  
	(DESCRIPTION =
		(ADDRESS_LIST =
		  (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.1.253)(PORT = 1521))
		)
		(CONNECT_DATA =
		  (SERVICE_NAME = orcl)
		)
	  )
		   ";
	   
	$db_username = "vinhoto";
	$db_password = "vinhoto";
	$con = new PDO("oci:dbname=".$tns,$db_username,$db_password);

	TORM\Connection::setConnection($con);
	TORM\Connection::setDriver("oracle");
	$pessoa = Pessoa::All();	
		
?>

Model: pessoa.php
<?php
   class Pessoa extends TORM\Model {}
   //pessoa::setOrder("nome");
   //pessoa::hasMany("fones",array("class_name"=>"Fone"));
   //pessoa::hasMany("contatos",array("class_name"=>"Contato"));
   
//    User::hasMany("tickets",array("class_name"=>"Ticket"));
   
?>

**Comment by cgarrotti** [comment]
Pelo q eu vi, problema de conexão nao deve ser pois este bloco: 
 $rst = self::resolveConnection()->query("select id from torm_info");
        if (!$rst->fetch()) {
            $stmt = self::resolveConnection()->query("insert into torm_info values (1)");
            self::closeCursor($stmt);
        }
        self::closeCursor($rst);

No qual ele faz um insert na torm_info, esta fazendo a inserção normal do valor 1 na tabela.

**Comment by taq** [comment]
Eu utilizo ele no Oracle de boa, mas tente trocar o caracter de escape do banco com:

```php
TORM\Driver::$escape_char = "";
```
Vou até dar uma olhada depois como está rodando, no esquema do caracter de escape.

**Comment by cgarrotti** [comment]
utilizando essa dica sua acima deu certo.

Eu hospedei a minha pagina, porem utilizando o banco mysql, aqui na minha maquina local testei tb com o mysql e nao houve erro algum, o erro so acontece la onde eu hospedei:

Non-static method TORM\Model::hasHasMany() should not be called statically in /home/u876719767/public_html/sis/torm/src/HasMany.php on line 85


dentro do model estado.php ha referencia a classe cidade:
 Estado::hasMany("cidades",array("class_name"=>"Cidade"));

porem da erro somente la no server

**Comment by taq** [comment]
Que versão do PHP está onde você hospedou?
Em 01/04/2016 11:31 AM, "cgarrotti" <notifications@github.com> escreveu:

**Comment by cgarrotti** [comment]
e a versao PHP Version 5.5.32
o link é esse:
http://cdg.esy.es/sis/info.php

2016-04-01 12:10 GMT-03:00 Eustáquio Rangel <notifications@github.com>:

**Comment by cgarrotti** [comment]
a minha versao que rodo aki local eh o  PHP Version 5.6.14  e la no site roda o 5.5.32

**Comment by taq** [comment]
Troque a linha

```php
public function hasHasMany($attr)
```
para

```php
public static function hasHasMany($attr)
```
no `HasMany.php` e veja se resolve. Parece que faltaram alguns métodos como estáticos, mas de alguma forma o PHP roda.

**Comment by taq** [comment]
Liberei uma nova versão já com a correção.

**Comment by cgarrotti** [comment]
Opa, blz
Vou atualizar aqui

2016-04-03 12:14 GMT-03:00 Eustáquio Rangel <notifications@github.com>:
