### ISSUE TITLE
Foreign Key 

### ISSUE THREAD

**Issue by marcelllo** [taq/torm#19]
Como faço para definir uma Foreign Key personalizada? O sistema utiliza o padrão %table%_id, porém se meu sistema não utilizar este padrão, não consigo fazer o select com chave estrangeira

**Comment by taq** [comment]
Existem as opções tanto para o atributo como para a classe, por exemplo, no `belongs_to`:

```php
Ticket::belongsTo("person", ["class_name"  => "User", "foreign_key" => "user_id"]);
```

**Comment by marcelllo** [comment]
Ótimo!
Deu certo. Muito obrigado!
