### ISSUE TITLE
Suporte a Postgres

### ISSUE THREAD

**Issue by coutofx** [taq/torm#20]
Eustáquio, parabéns pelo projeto! Você tem intenção de criar driver para Postgres ?

**Comment by taq** [comment]
Olá, obrigado!

O suporte aos diversos bancos de dados é dado pelo PDO, e não pelo TORM. :-)

http://wiki.locaweb.com.br/pt-br/Conectando-se_ao_Postgre_usando_PDO

**Comment by taq** [comment]
Segunda a noite é um saco, eu acabo respondendo comentário dormindo, acabei confundindo o TORM com outro projeto ehehehe ... o driver para Postgresql é facinho criar, é só seguir o exemplo dos outros. Quando tiver um tempo aqui eu dou uma olhada lá.

**Comment by coutofx** [comment]
Blz amigo, fico grato e vou utilizar sua ORM pois gostei muito.

**Comment by taq** [comment]
Oi, você poderia pegar o código da branch `postgresql`  e verificar se está funcionando ok?

**Comment by taq** [comment]
Ahn, oi?

**Comment by taq** [comment]
Esquenta não, amigo, fiz por aqui. :-p
