### ISSUE TITLE
One-To-One error

### ISSUE THREAD

**Issue by cgarrotti** [taq/torm#22]
Ola amigo tudo bom ?
Parabens pelo seu framework, estou utilizando ele em um pequeno projeto meu e tem me ajudado demais.

Estou com um problema em relacionamento, as estruturas das tabelas sao as seguintes:

CREATE TABLE `CLIENTE_TELEFONE` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`TELEFONE_ID`	INT NOT NULL,
	`CLIENTE_ID`	INT NOT NULL,
	FOREIGN KEY(`TELEFONE_ID`) REFERENCES `TELEFONE`(`ID`),
	FOREIGN KEY(`CLIENTE_ID`) REFERENCES `CLIENTE`(`ID`)
);

CREATE TABLE `TELEFONE` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`NUMERO`	NUMERIC(15),
	`EXCLUIDO`	VARCHAR(1)
);

estou fazendo esse relacionamento no torm:

Telefone::belongsTo("cliente_telefone",       ["class_name"  => "cliente_telefone", "foreign_key" => "telefone_id"]);
	Cliente_Telefone::hasOne("telefone",  ["class_name"  => "telefone", "foreign_key" => "id"]);

e depois pegando os valores:

foreach($cliente->cliente_telefone as $cliente_telefone) {
			
			$aCliente_Telefone[] = array($cliente_telefone->id, 'fone' => $cliente_telefone->telefone->numero);
		}

porém esse $cliente_telefone->telefone->numero   está me retornando o erro:
 Trying to get property of non-object,
não sei onde está o erro de relacionamento ai de um-para-um.

Abraço

Charles

**Comment by taq** [comment]
A primeira coisa que você tem ou regularizar nas tabelas ou no código, é a pluralização. Suas tabelas são chamadas `CLIENTE_TELEFONE` e `TELEFONE`, quando que pelo padrão, teriam que ser no plural. Um objeto (singular) é uma linha da tabela (plural), então por exemplo a tabela `TELEFONE` teria que chamar `TELEFONES`. A outra é mais complicada pois tem nome composto, acabaria sendo `CLIENTE_TELEFONES`.

Também as associações estão erradas. Se `Telefone` `belongsTo` um `cliente_telefone`, a tabela `TELEFONE` deve armazenar o atributo `cliente_telefone_id`, porque em uma associação de dependência como a `belongs`, é responsabilidade da origem (`Telefone`) indicar onde que ela pertence (`Cliente_Telefone`). Desse jeito também a `hasOne` vai conseguir encontrar o registro na outra tabela.

Também o nome da classe vai ficar meio estranho com sublinhado no meio, seria melhor o *camel case* como `ClienteTelefone`. 

Dá uma olhada na página do Wiki sobre associações: https://github.com/taq/torm/wiki/Associations

E recomendo você dar uma brincada com o ActiveRecord, de onde eu descaradamente copiei alguns dos recursos do TORM, para entender como funcionam as associações: http://guides.rubyonrails.org/association_basics.html

Se eu fosse você, eu consideraria **fortemente** o framework Ruby on Rails. Um dos motivos que eu fiz o TORM foi desespero de não poder utilizar ele em um cliente que só utilizava PHP. :-)

**Comment by taq** [comment]
Vou fechar o issue, já que não é problema no código, beleza?

**Comment by cgarrotti** [comment]
Blz, eu fiz uma implementação no framework, coloquei uma função de join. Exemplo User::setJoin('Tabela', 'CampoLigacao1', 'CAmpoLigacao2', 'CampoRetorno'). Testei aqui e está funcionando, legal seria complementar esse CampoRetorno como array, ai me retornaria x campos que eu iria precisar.

**Comment by taq** [comment]
Como eu te expliquei, o `join` já é feito de forma implícita, pelo uso de associações de modo *correto*, de acordo com as convenções do ORM. O retorno do `join` é automaticamente uma instância de um objeto, o que mantém a consistência.
Se você fez as associações de outro jeito do que o esperado pelo ORM, como você especificou acima, e fez um método customizado para o seu uso, tudo bem, mas como disse, a funcionalidade já existe desde que sejam seguidas as convenções.
