### ISSUE TITLE
mktime() Error

### ISSUE THREAD

**Issue by cgarrotti** [taq/torm#23]
Eu publiquei o meu site em http://agendateste.esy.es/teste1/   porém esta me retornando o seguinte erro:
http://agendateste.esy.es/teste1/

Strict Standards: mktime(): You should be using the time() function instead in /home/u657493626/public_html/teste1/orm/src/Cache.php on line 128

ja fiz a troca la no Cache.php de mktime para time, porém ainda continuou com erros. O PHP que roda lá é o PHP Version 5.6.21

**Comment by taq** [comment]
Se você trocou para `time()`, essa mensagem deve ter sumido. O que aparece depois? No `strict` o warning é publicado, mas o código roda. Deve ser alguma outra coisa que não está legal.

De qualquer maneira o PHP no servidor que você está utilizando está ativo o modo `strict`, você pode desabilitar para ter menos mensagens de erros. Apesar que seria uma boa eu já mudar para a `time()`. 

Você pode consultar mais informações aqui: http://php.net/manual/pt_BR/errorfunc.configuration.php#ini.display-errors

**Comment by taq** [comment]
De qualquer forma, acabei de enviar código atualizado com todos os warnings de erros ativados, só havia as `mktime()` e uma ou duas chamadas de métodos estáticos erradas. :-)

**Comment by cgarrotti** [comment]
Aqui deu certo também. Estava dando um erro nada a ver na Cache.php, mas era coisa da minha classe o erro. Vou baixar novamente os fontes do framework

**Comment by taq** [comment]
Beleza! Obrigado por avisar da `mktime()`!

**Comment by cgarrotti** [comment]
Por nada ! Vou mexendo, conforme for descobrindo algo errado, eu posto
Valeu
