### ISSUE TITLE
Monitor SQL

### ISSUE THREAD

**Issue by cgarrotti** [taq/torm#25]
Como eu faço para monitor as SQL enviadas ao banco ? Por exemplo, ao fazer isso:

$teventss = TEvents::where(array("cliente"=>$id_cliente,"finalizado"=> 'S', "baixado" => $statusBaixa));

Como retornar a SQL que foi enviado ao Banco ?

Att

Charles

**Comment by taq** [comment]
Só daria para fazer isso pedindo para ver qual o SQL antes de enviar ele para os blocos de `self::resolveConnection()->query($sql)`. Taí uma boa idéia de implementar isso em `Connection` e alterar os métodos para usar o método novo ao invés de enviar direto para a conexão.

**Comment by taq** [comment]
Ou interceptar direto na função `query`. O x da coisa é: monitorar que jeito? Mostrar na tela? Gravar em um log? Gravar em um log seria mais legal.

**Comment by cgarrotti** [comment]
Isso mesmo, gravar um arquivo log seria bem útil para sabermos o que esta sendo enviado.

**Comment by cgarrotti** [comment]
Só não tenho idéia onde fazer isso.

**Comment by taq** [comment]
Já temos suporte à logs. É só implementar para gravar em algum lugar, ao invés de mostrar na tela.

**Comment by taq** [comment]
Feito: https://github.com/taq/torm/wiki/Log
