### ISSUE TITLE
save method returning true but not is saving anything.

### ISSUE THREAD

**Issue by arturcesarmelo** [taq/torm#26]
The connection is ok.

I know that because i tried to change the table name of a model for one which not exists and **postgres** thrown a fatal error.

Here is what i'm trying to do:
```php
require_once 'bootstrap.php';

$calling = new \App\Calling();

$calling->id = 'a';
dd($calling->save());
```

As you can see, i'm trying to insert a string into a `id` field which is `integer`. The dump method, dd(), is showing me `true`, like if everything was fine. Of course nothing was stored on databases.

Could any one explain me what i'm doing wrong?

here is my connection method

```php
$db 	= getenv('DB_DATABASE');
$host 	= getenv('DB_HOST');
$dbuser = getenv('DB_USERNAME');
$dbpass = getenv('DB_PASSWORD');
$dns = "pgsql:host=$host;port=5432 dbname=$db user=$dbuser password=$dbpass";
$con = new \PDO($dns);
\TORM\Connection::setConnection($con);
\TORM\Connection::setDriver("pgsql");
```

**Comment by taq** [comment]
No answer after some months, closing.
