### ISSUE TITLE
Este ORM permite fazer pesquisas limitando quais campos retornar?

### ISSUE THREAD

**Issue by dougkusanagi** [taq/torm#27]
Boa tarde. Não sei se é correto postar perguntas aqui, se não, eu gostaria de saber onde...Venho usando o TORM pois achei incrivelmente fácil, intuitivo e leve...mas recentemente precisei especificar quais campos quero pegar na minha pesquisa, já que meu BD está bem grande e acho que um `"SELECT campo1, campo2"` vai aumentar a performance da busca em comparação ao `"SELECT *"` que acho que o ORM faz por padrão.

Li a Wiki do TORM que é muito organizada por sinal, porém não encontrei nada a respeito...por acaso ele permite fazer isso?

Obrigado.

**Comment by taq** [comment]
Oi! 

Para ser sincero faz um tempão que eu mesmo não uso ele, mas os campos ficam lá na classe Builder, montados a partir da linha 50:

https://github.com/taq/torm/blob/9db401ffd313af1b54e769cae90c00d6fce8dc81/src/Builder.php

Os campos são recuperados do Finder:

https://github.com/taq/torm/blob/9db401ffd313af1b54e769cae90c00d6fce8dc81/src/Finders.php

Que são recuperados da classe Model, na linha 396:

https://github.com/taq/torm/blob/9db401ffd313af1b54e769cae90c00d6fce8dc81/src/Model.php

Esses campos são preenchidos dando uma olhada nas colunas da tabela. 

Daria para fazer um "curto-circuito" ali, indicando quais campos pegarem, o duro que estou sem um Oracle aqui para testar.

**Comment by dougkusanagi** [comment]
Olá, agradeço a resposta.
Acho que já li esses arquivos durante a pesquisa, vou reler e tentar entender como faria, mas acho que não dou conta não, de qualquer jeito, obrigado pelo direcionamento rs
