### ISSUE TITLE
Associação seria possível com namespace?

### ISSUE THREAD

**Issue by dougkusanagi** [taq/torm#31]
Olá, sei que não mantém mais o código e desculpa incomodar de novo, mas poderia me tirar outra dúvida? É possível fazer uma associação num app que usa namespace passando-o junto com o nome da classe, por exemplo um:

`belongsTo("App\Model\Categoria")`

Só pra saber como fazer...Obrigado.

**Comment by Felyp-Henrique** [comment]
Opa, não sou autor do 'source' mas estou acompanhando com mais sutileza. Eu também não fui a fundo no 'source' mas percebi que as tabelas são relacionadas de forma autônoma com o nome da classe modelo. Os campos das tabelas também apresenta o mesmo comportamento, que significa dizer que se você passar como uma string o nome completo e qualificado de uma classe em um 'namespace' não funcionara. O que o 'belongsTo' e demais métodos derivados da classe Model espera, é uma string dizendo o nome da tabela equivalente ao do banco de dados. Logo sua estratégia não funcionará como esperado.

**Comment by Felyp-Henrique** [comment]
Vale a pena advertir que a reposta se baseia apenas na experiência de ter usado o 'library'.
